#Show by id
#get http://127.0.0.1:8000/api/employees/1

#Show all employees (could filter on order, sort and search if empty show all)
#get http://127.0.0.1:8000/api/employees/?sort=id&order=desc&search=Pfeffer

# #Create employee
# POST http://127.0.0.1:8000/api/employees/
# Content-Type: application/json

# {
#     "first_name": "Bob",
#     "last_name": "De Bouwer",
#     "email" : "test@test.be",
#     "salary" : 1600,
#     "password" : "test",
#     "address_id" : 1,
#     "job_id" : 2
# }

#Soft-delete employee
#DELETE http://127.0.0.1:8000/api/employees/15

#restore soft-deleted employee
#PUT http://127.0.0.1:8000/api/employees/15/restore

#update employee
# PUT http://127.0.0.1:8000/api/employees/15
# Content-Type: application/json

# {
#     "first_name" : "beb"
# }

#Show by id
#get http://127.0.0.1:8000/api/jobs/1

# # #Create Job
# POST http://127.0.0.1:8000/api/jobs/
# Content-Type: application/json

# {
#     "job_title" : "Tester"
# }

#Soft-delete employee
#DELETE http://127.0.0.1:8000/api/jobs/11

#restore soft-deleted employee
# PUT http://127.0.0.1:8000/api/jobs/11/restore

#update employee
# PUT http://127.0.0.1:8000/api/jobs/11
# Content-Type: application/json

# {
#     "job_title" : "Programmer"
# }
