#Show all employees 5 per page
#get http://127.0.0.1:8000/api/employees?page=2

#Show one employee based on id
# get http://127.0.0.1:8000/api/employees/show_by_id/id=1

#Create new employee
# post http://127.0.0.1:8000/api/employees/create
# content-type: application/json

# {
#     "first_name":"John",
#     "last_name":"Doe",
#     "email":"john@gmail.com",
#     "password":"test",
#     "salary": 1600,
#     "address_id": 1,
#     "job_id": 2
# }

#Delete employee
#get http://127.0.0.1:8000/api/employees/delete/email=john@gmail.com

#Restore employee
#get http://127.0.0.1:8000/api/employees/restore/email=john@gmail.com

#Update employee
# post http://127.0.0.1:8000/api/employees/update
# content-type: application/json

# {
#     "id": 11,
#     "first_name":"Jan",
#     "last_name":"Doe"
# }

#filter the employees
# get http://127.0.0.1:8000/api/employees/filter
# content-type: application/json

# {
#     "sort": "id",
#     "order": "asc",
#     "search": "y"
# }

#Show all jobs 5 per page
#get http://127.0.0.1:8000/api/jobs

#Show one job based on id
#get http://127.0.0.1:8000/api/jobs/show_by_id/id=11

#Create new job
# post http://127.0.0.1:8000/api/jobs/create
# content-type: application/json

# {
#     "job_title":"Programmer"
# }

#Delete job
#get http://127.0.0.1:8000/api/jobs/delete/title=Programmer

#Restore job
#get http://127.0.0.1:8000/api/jobs/restore/title=Programmer

#Update job
# post http://127.0.0.1:8000/api/jobs/update
# content-type: application/json

# {
#     "id": 11,
#     "job_title": "Tester"
# }

#filter the jobs with 5 on each page
#  get http://127.0.0.1:8000/api/jobs/filter
#  content-type: application/json

#  {     
#     "sort": "hallo",
#     "order": "desc"
#  }
